#!/usr/bin/env sh

setxkbmap -model pc105 -layout us,ru -option grp:alt_shift_toggle -option caps:swapescape
xset r rate 300 50
[ "$(xrandr | grep -c "[^(dis)]connected")" = 2 ] && xrandr --output HDMI-2 --auto --left-of eDP-1 --mode 1920x1080

xsetroot -solid "#737373"

tint2 &
nm-applet &
dunst &
python ~/.config/dwm/main.py &
